# The west manifest file for upstream Zephyr.
#
# The per-installation west configuration file, .west/config, sets the
# path to the project containing this file in the [manifest] section's
# "path" variable.
#
# You are free to create your own manifest files and put them in any
# repository you want, to create your own custom Zephyr installations.
# For example, you could create a manifest file in your own out of
# tree application directory, which would pull this zephyr repository
# in as an ordinary project.
#
# You can pass your manifest repositories to west init when creating a
# new Zephyr installation. See the west documentation for more
# information.

manifest:
  defaults:
    remote: upstream

  remotes:
    - name: upstream
      url-base: https://github.com/zephyrproject-rtos
    - name: danieldegrasse
      url-base: https://github.com/danieldegrasse

  #
  # Please add items below based on alphabetical order
  projects:
    - name: hal_nxp
      revision: 4c992b5db0ea6960f910199dd50310d0f7a766c7
      remote: danieldegrasse
      path: modules/hal/nxp
      groups:
        - hal
    - name: cmsis
      revision: 74981bf893e8b10931464b9945e2143d99a3f0a3
      path: modules/hal/cmsis
      groups:
        - hal
    - name: mcuboot
      revision: 9fc844dc7f3f285f0d5c5687f18eb8b60e3bc0ad
      remote: danieldegrasse
      path: bootloader/mcuboot
    - name: lvgl
      revision: 5ab83099854719ed326b6ecb9b09b07b1eee4818
      path: modules/lib/gui/lvgl
      remote: upstream
    - name: mbedtls
      revision: 6e166050075688fd3cf3d0cb3fc34a1c52df2496
      path: modules/crypto/mbedtls
      groups:
        - crypto
    - name: zephyr
      revision: 69346561e3309b8d402a896e4bbe4c8a84b51470
      remote: danieldegrasse
      path: zephyr
      import: false
      west-commands: scripts/west-commands.yml
    - name: zmk
      revision: 74dde25093535517649de6479f0b7aa0d87746e7
      remote: danieldegrasse
      path: apps/zmk
      import: false
      west-commands: app/scripts/west-commands.yml

  self:
    path: apps
